config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users
  get 'pages/info'
  root to: redirect('/ideas')
  resources :ideas
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
       if user.admin?
        can :manage, :all
       else
        can :manage, Idea, user_id: user.id
        can :manage, Comment, user_email:user.email
        can :read, :all
       end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :idea
end

app/models/idea.rb
class Idea < ApplicationRecord
    belongs_to :user
    has_many :comments
    mount_uploader :picture, PictureUploader
    scope :search, ->(query) { where("name like ?", "%#{query}%") }
end

app/models/user.rb
class User < ApplicationRecord
	has_many :ideas
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
    #@comment.user_email = current_user.email
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.user_email = current_user.email
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comentario criado com sucesso' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comentario Editado' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comentario excluido' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_email, :body, :idea_id)
    end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  load_and_authorize_resource
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  # GET /ideas
  # GET /ideas.json
  def index
    if params[:search]
    @ideas = Idea.all.search(params[:search])
    else
      @ideas = Idea.all
    end
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
    @comments = @idea.comments.all
    @comment = @idea.comments.build
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)
    @idea.user_id = current_user.id
    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:name, :description, :picture)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <!--<div class="field">
    <%= form.label :user_email %>
    <%= form.text_field :user_email %>
  </div>-->
  
<!--<%= form.hidden_field :user_email %>-->

  <div class="field">
    <!--<%= form.label :body %>-->
    <hr>
    <p><b>COMENTARIO:</b></p>
    <%= form.text_area :body %>
  </div>

  <%= form.hidden_field :idea_id %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editar Comentário</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Ver mais', @comment %> |
<%= link_to 'Voltar', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comentários:</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Comentario</th>
      <th>Publicação</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user_email %></td>
        <td><%= comment.body %></td>
        <!--<td><%= comment.idea_id %></td>-->
        <td><%if can? :read, comment%><%= link_to 'Ver mais', comment %><%end%></td>
        <td><%if can? :update, comment%><%= link_to 'Editar', edit_comment_path(comment) %><%end%></td>
        <td><%if can? :destroy, comment%><%= link_to 'Excluir', comment, method: :delete, data: { confirm: 'Are you sure?' } %><%end%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo comentário', new_comment_path %>

app/views/comments/new.html.erb
<h1>Novo Comentário</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Voltar', :back %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @comment.user_email %>
</p>

<p>
  <strong>Comentário:</strong>
  <%= @comment.body %>
</p>

<!--<p>
  <strong>Idea:</strong>
  <%= @comment.idea_id %>
</p>-->

<%if can? :update, @comment%><%= link_to 'Editar', edit_comment_path(@comment) %> | <%end%>
<%= link_to 'Voltar', :back %>

app/views/ideas/_form.html.erb
<%= form_with(model: idea, local: true) do |form| %>
  <% if idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
        <% idea.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editando Publicação</h1>

<%= render 'form', idea: @idea %>

<%= link_to 'Ver mais', @idea %> |
<%= link_to 'Voltar', ideas_path %>

app/views/ideas/index.html.erb
<p id="notice"><%= notice %></p>
<div class="border">
<div class="title">
  <h1>Publicações</h1>
</div>
<div class="mt-3 ml-3">
<%= form_tag(ideas_path, method: "get") do %>
    <%= label_tag(:q, "Buscar por:") %>
    <%= text_field_tag("search") %>
    <%= submit_tag("buscar") %>
<% end %>
</div>

<div class="content">
<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Descrição</th>
      <th>Imagem</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><b><%= idea.name %></b></td>
        <td><%= idea.description %></td>
        <td><%= image_tag idea.picture_url, width: 100 if idea.picture.present? %></td>
        <td><%= link_to 'Ver mais', idea %></td>
        <td><%if can? :update, idea%><%= link_to 'Editar', edit_idea_path(idea) %><%end%></td>
        <td><%if can? :destroy, idea%><%= link_to 'Excluir', idea, method: :delete, data: { confirm: 'Tem certeza que deseja excluir essa publicação?' } %><%end%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova publicação', new_idea_path %>
</div>
</div>

app/views/ideas/new.html.erb
<h1>Nova Publicação</h1>

<%= render 'form', idea: @idea %>

<%= link_to 'Voltar', ideas_path %>

app/views/ideas/show.html.erb
<p>
  <strong>Titulo:</strong>
  <%= @idea.name %>
</p>

<p>
  <strong>Descrição:</strong>
  <%= @idea.description %>
</p>

<p>
  <strong>Imagem:</strong>
  <%= image_tag(@idea.picture_url, width: 200) if @idea.picture.present? %>
  <h3>Comentários</h3>
  <hr>
  <% @comments.each do |comment| %>
  <div>
    <strong><%= comment.user_email %></strong>
    <br>
    <p><%= comment.body %></p>
    <p><%if can? :destroy, comment%><%= link_to 'Deletar', comment_path(comment), method: :delete, data: { confirm: 'Tem certeza que deseja deletar esse comentario?' } %><%end%></p>
  </div>
<% end %>
<%= render partial: 'comments/form', locals: { comment: @comment } %>
</p>

<%if can? :update, @idea%><%= link_to 'Editar', edit_idea_path(@idea) %> |<%end%>
<%= link_to 'Voltar', ideas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AchadosEPerdidos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="../../assets/style_new.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg  ">
  <div class="container">
    <img  src="https://haxe.org/img/branding/haxe-logo-glyph.png" height="60" width="60">
    <a class="navbar-brand" href="/">Achados e Perdidos</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon">VER MAIS</span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/ideas">Publicações</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="/pages/info">Quem somos?</a>
        </li>
      </ul>

      <p class="navbar-text float-right">
<% if user_signed_in? %>
  Logado como: <strong><%= current_user.email %></strong>.
  <%= link_to 'Editar perfil', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Registrar-se", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

    </div>
  </div>
</nav>
  <div class="container">
  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
  <%= yield %>
</div>
  </body>
  <footer>
  <div class="container">
  </div>
</footer>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
</html>